{% set version = "0.20.2" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: kmeans-wheels.tar.gz
  url: https://github.com/jeremiedbb/scikit-learn/archive/kmeans-wheels.tar.gz
  sha256: 416f54956d02052638fc60d369d3de34d05ceaa52951aef03c7d23d0ff89ab1b

build:
  number: 1401
  # We lack scipy on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - numpy
    - scipy
    - pytest
    - clangdev 4.0*  # [osx]
    # - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy
    - clangdev 4.0*  # [osx]
    # - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]

test:
  requires:
    - pytest
  imports:
    - sklearn
  commands:
    - OPENBLAS_NUM_THREADS=1 pytest --verbose --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
